### ISSUE TITLE
Error sometimes thrown out when some pawn are melee fighting each other

### ISSUE THREAD

**Issue by GervyMaglina** [cseelhoff/RimThreaded#260]
**Describe the bug**
Melee fighting pawn(1v1) sometimes cause errors to pop out 

**To Reproduce**
1. Create a new world
2. Click on the "debug actions menu"
3. Click "Do Incident 10x (Map)" and select "RaidEnemy", trigger it twice or more for better results
4. Wait for the errors to appear

**Error Log**
https://gist.github.com/GervyMaglina/f3870b419f2cb99648d66d89704ad54b

Extra errors(not in current save file)-
https://gist.github.com/GervyMaglina/bd3dc7d85bce12d0e4f895b3a0a08a00

**Screenshots**
![Screenshot (4)](https://user-images.githubusercontent.com/72695469/99902581-ccd63000-2cf9-11eb-8680-94158c00c16a.png)
![Screenshot (5)](https://user-images.githubusercontent.com/72695469/99902585-d2cc1100-2cf9-11eb-87a5-2e9fa20624be.png)
These images shows that they will immediately on standing behaviour before they start to fight again

**Comment by GervyMaglina** [comment]
**Loaded Mod**
Harmony
Rimthreaded
Core
Mod Manager

**Comment by cseelhoff** [comment]
Thank you for the bug submission! I will look into it

**Comment by bababooeyy** [comment]
Can confirm that this is still happening in prerelease 1.2.6, however it seems to be very rare and does not appear to affect gameplay in any way, although it's very hard to track this since I had to spawn so many raids to get the error. A lot of other errors also happened in these logs, but the one stated above is the last one in the log.

Log:
https://gist.github.com/28c2d3649e7be359d7e23f9aa6f28804

Save: 
https://drive.google.com/file/d/13P-8zRlFdL6ihYjhdUO59q7S0_oBgYvl/view?usp=sharing

**Comment by cseelhoff** [comment]
fixed in 1.3.0.9 PREVIEW
