### ISSUE TITLE
MapCellsInRandomOrder ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by xywf221** [cseelhoff/RimThreaded#284]
**Describe the bug**
I'm driving my ship down at the map point, and he's always reporting errors on the way.
according to the latest source code, I found the reason for this exception.
``` c#
int cycleIndex = (steadyEnvironmentEffectsCycleIndexOffset - index) % steadyEnvironmentEffectsArea;
IntVec3 c = steadyEnvironmentEffectsCellsInRandomOrder.Get(cycleIndex);
```
exception reason : ```cycleIndex  >= steadyEnvironmentEffectsCellsInRandomOrder.map.Area```
I changed it a little bit
```c#
int cycleIndex = (steadyEnvironmentEffectsCycleIndexOffset - index) % steadyEnvironmentEffectsArea;
if (cycleIndex >= steadyEnvironmentEffectsArea)
{
	cycleIndex = 0;
}
IntVec3 c = steadyEnvironmentEffectsCellsInRandomOrder.Get(cycleIndex);
```
Since I don't know how I can't PR, I ask a Issue. Hope to help you.

**Error Log**
```c#
Exception ticking steadyEnvironmentEffectsCells 38: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <567df3e0919241ba98db88bec4c6696f>:0 
  at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <567df3e0919241ba98db88bec4c6696f>:0 
  at Verse.MapCellsInRandomOrder.Get (System.Int32 index) [0x00012] in <6326ac03f61f45efb3178f3bfd084139>:0 
  at RimThreaded.RimThreaded.ExecuteTicks () [0x00613] in <2702e3b9302a4c3d9fce6ccb2bbae8b5>:0
```

**Comment by xywf221** [comment]
And here
```c#
                    int cycleIndex = (WildPlantSpawnerCycleIndexOffset - index) % WildPlantSpawnerArea;
                    try
                    {
                        IntVec3 intVec = WildPlantSpawnerCellsInRandomOrder.Get(cycleIndex);

                        if ((WildPlantSpawnerCycleIndexOffset - index) > WildPlantSpawnerArea)
                        {
```
no restrictions

**Comment by Niilo007** [comment]
---

**Please see:**

* [Q&A](https://github.com/cseelhoff/RimThreaded/wiki/Q&A)

* [Mod Compatibility](https://github.com/cseelhoff/RimThreaded/wiki/Mod-Compatibility)

* [Known Issues](https://github.com/cseelhoff/RimThreaded/projects/1?fullscreen=true)

* The [Community Modpack](https://github.com/pastorismylord/Community-Modpack)

* This [Mod Order Guide](https://rwom.fandom.com/wiki/Mod_Order_Guide)

**Address the problems in your mod list before asking for help or submitting errors & bug reports!**

* You can submit a bug report [here](https://github.com/cseelhoff/RimThreaded/issues/new/choose)

* If your submitted issue gets closed and the bug is still happening you can re open the issue.

---
