### ISSUE TITLE
lag after research something and unity crash when quit game

### ISSUE THREAD

**Issue by 136068448** [cseelhoff/RimThreaded#291]
**Describe the bug**
i don't know if it can be reproduct.
i just start a new game and test some thing include call 20 caravan, call 20 animal migration,set pawn all skill to level20 and research something,and quit game, then it crashed

**Error Log**
player.log
https://gist.github.com/136068448/9ba209f5fb7391669ba2ac753b1875b0
error.log
https://gist.github.com/136068448/4485e3daba7de43282ae8be900c90f0c

**Comment by cseelhoff** [comment]
It crashes during the game or it crashes after you quit the game?

**Comment by 136068448** [comment]
after quit the game

**Comment by cseelhoff** [comment]
Ok. Yes. I have also witnessed this. Unfortunately, the error log does not give me much for hints. Since it affects gameplay close to zero, and its hard to fix, I won't probably prioritize this.

**Comment by cseelhoff** [comment]
It looks like you actually have 2 bugs in this game. It looks like your player.log refers to an error in pathing... Could you create a separate bug report for that using one of the bug templates, including how to reproduce? https://github.com/cseelhoff/RimThreaded/issues/new/choose

**Comment by 136068448** [comment]
OK，i will create a new report about pathing problem

**Comment by Niilo007** [comment]
---

**Please see:**

* [Q&A](https://github.com/cseelhoff/RimThreaded/wiki/Q&A)

* [Mod Compatibility](https://github.com/cseelhoff/RimThreaded/wiki/Mod-Compatibility)

* [Known Issues](https://github.com/cseelhoff/RimThreaded/projects/1?fullscreen=true)

* The [Community Modpack](https://github.com/pastorismylord/Community-Modpack)

* This [Mod Order Guide](https://rwom.fandom.com/wiki/Mod_Order_Guide)

**Address the problems in your mod list before asking for help or submitting errors & bug reports!**

* You can submit a bug report [here](https://github.com/cseelhoff/RimThreaded/issues/new/choose)

* If your submitted issue gets closed and the bug is still happening you can re open the issue.

---
