### ISSUE TITLE
bug about pathing (might be non issue(possibly fixed))

### ISSUE THREAD

**Issue by 136068448** [cseelhoff/RimThreaded#301]
**Describe the bug**
this bug will appear when have a number of animal entry map, and this bug will cause thing similar as #253 #281 #243 sometime, i will provide the GIF about the animal can't move(and i think it just the animal try to fing pathway)

**To Reproduce**
1. choose ice sheet or other bime to start(i don't know the reason but it cause lag or make game frozzen observably in ice sheet,other biome seems just a error message and a little affect with performance)
2. build a home for pawns
3. select incident*10 in dev menu
4. select HerdMigration
5. See error

**Error Log**
https://gist.github.com/136068448/547a2d6fac367950815afb3b8952de59

**Screenshots**
https://imgur.com/GgR1Ylp

**Comment by bababooeyy** [comment]
A bug does occur in 1.2.6 preview, but I don't think its the same one. It also happens much less frequently, roughly once per incident. The animals also can move just fine. 

Log:
https://gist.github.com/15c8621a286075a3e97df5cf687ee042

Save: 
https://drive.google.com/file/d/1lWJ8OtmTkfdqcKnbAesbdLmd2btf1IGk/view?usp=sharing

This bug is really easy to reproduce though, so you don't really need to download the save. I'll just attach it here for convenience i guess.

**Comment by Niilo007** [comment]
Re open if issue happens again
