### ISSUE TITLE
(Problem causer quest) "Giant smoke cloud" game condition slows game to 100 TPS

### ISSUE THREAD

**Issue by Casmeron** [cseelhoff/RimThreaded#332]
**Describe the bug**

I got a "Mech cluster with a smoke spewer" quest (where it lands on the map a few tiles away and you need to caravan out to destroy it). Not sure if it's vanilla or VFE. 

Once the "giant smoke cloud" game condition, I was unable to push my TPS past about 100 regardless of what I did. 

I used devmode to remove the spewer and "giant smoke cloud" effect & my game returned to normal. 

**To Reproduce**

1. Go to world map. 
2. Open the dev menu and click "Spawn Site"
3. Click "Smoke Spewer" and spawn it near your base
4. watch game slow down

**Error Log**
No errors, game just got very slow

**Comment by JoJo1541** [comment]
Can you provide a savegame by any chance?

**Comment by Niilo007** [comment]
noticed the same thing but with a "EMI Dynamo" when i destroyed it the game started running well again. (it was a enemy camp quest)

**Comment by cseelhoff** [comment]
@JoJo1541 Were you able to find anything more about this by chance? I had a hard time reproducing the error myself.

**Comment by JoJo1541** [comment]
I can reproduce it. I can take a look at it as soon as my Profiler works again.

**Comment by JoJo1541** [comment]
The issue seems to correlate with planet size.

5% No observable difference
30% from about 900 down to 600-800
100% from about 900 down to 35

Profiling is pointing to WorldFloodFiller.FloodFill_Patch.FloodFill
![2020-12-13 21_16_07-JetBrains dotTrace Timeline Viewer](https://user-images.githubusercontent.com/5374156/102022665-933c9600-3d88-11eb-81f6-4e6455653ad9.png)

**Comment by Niilo007** [comment]
fixed in 1.2.7
