### ISSUE TITLE
"Zombieland" spam error 

### ISSUE THREAD

**Issue by Deamonsol** [cseelhoff/RimThreaded#337]
**Describe the bug**
Exception ticking error for every entity loaded

**To Reproduce**
1. load modlist
2. start new colony 
3. enjoy the color red

[Load Order - It loads.txt](https://github.com/cseelhoff/RimThreaded/files/5633315/Load.Order.-.It.loads.txt)

[new game spam error.txt](https://github.com/cseelhoff/RimThreaded/files/5633319/new.game.spam.error.txt)

**Comment by 15adhami** [comment]
Tested with RT 1.3.2 and 2.0.7. Created a new colony with just RT and Zombieland loaded. Many thread timeouts as soon as the map loads, and causes all pawns/animals to freeze. Game cannot be played. Happens in both 1.3.2 and 2.0.7.

**Comment by thefriendlycacti** [comment]
This can be temporarily taken care of by disabling "Automatic avoidance of zombies" in Zombieland settings, however due to zombies having custom pathing to save on recourses, those that spawn will be unable to path and you will start receiving "ran out of cells to process" and will bring the game to a halt.

**Comment by pastorismylord** [comment]
compatibility seems achieved on 2.1.5, further testing is required.

**Comment by pastorismylord** [comment]
tested 2.2.8 and Zombieland. Game freezes as soon as the map loads. paging Dr @cseelhoff
