### ISSUE TITLE
Deep drill unable to be operated

### ISSUE THREAD

**Issue by Energywelder** [cseelhoff/RimThreaded#385]
**Describe the bug**
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report.  (Didnt see anything that sounded similar)
Neither Colonists nor non-colonist workers can access the deep drill. I can not order them to focus on working at the deep drill as right-clicking on the deep drill shows no jobs available (reflected in log file, UI exception)

**To Reproduce**

**Error Log**
Link to contents of Player.log or Error.log (Please use something like gist or pastebin. DO NOT PASTE HERE)
https://pastebin.com/qjKKMMnG

**Mod List**
Paste contents of ModList used when bug occurred.
https://gist.github.com/9273f9f05e6750e7935678a6a5a4751c

**Screenshots**

**Comment by Niilo007** [comment]
---

**Please see:**

* [Q&A](https://github.com/cseelhoff/RimThreaded/wiki/Q&A)

* [Mod Compatibility](https://github.com/cseelhoff/RimThreaded/wiki/Mod-Compatibility)

* [Known Issues](https://github.com/cseelhoff/RimThreaded/projects/1?fullscreen=true)

* The [Community Modpack](https://github.com/pastorismylord/Community-Modpack)

* This [Mod Order Guide](https://rwom.fandom.com/wiki/Mod_Order_Guide)

**Address the problems in your mod list before asking for help or submitting errors & bug reports!**

* You can submit a bug report [here](https://github.com/cseelhoff/RimThreaded/issues/new/choose)

* If your submitted issue gets closed and the bug is still happening you can re open the issue.

---
