### ISSUE TITLE
Red error that didn't cause any issues: Force sleeping colonist to build unfinished bed

### ISSUE THREAD

**Issue by UndeadKitten** [cseelhoff/RimThreaded#400]
**Describe the bug**
No noticeable issues, only an error log popup with the red error, I explain when it occurred below. I was about 10 minutes into a new game, with a freshly installed Rimworld and config folder. I only have Harmony and RimThreaded installed, and I don't have Royalty DLC.
EDIT: Version was RT 1.2.3

**To Reproduce**
1. Have an unfinished wooden bed with some of the materials in it already
2. Select a colonist that is assigned to constructing who is also sleeping
3. Right click the unfinished bed
4. Force the colonist to build the bed
5. See error (Exception in CheckCurrentToilEndOrFail)

**Error Log**
https://gist.github.com/UndeadKitten/f4c9cd69b57dc739b3c2f921466715df

**Specs**
Operating System: Windows 10 Home 64-bit
Processor: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 CPUs), ~3.5GHz
Memory: 16384MB RAM
Card name: NVIDIA GeForce GTX 970

**Comment by Eldulac** [comment]
**[Tested on RT 1.3.2]**
I tested the save UndeadKitten had posted to another report here, which is about 10 minutes further into the game than the issue reported here.
[Esora (Permadeath).zip](https://github.com/cseelhoff/RimThreaded/files/6137370/Esora.Permadeath.zip)

I ran the game for about a week in-game, but was unable to replicate this problem, despite following the steps described in the report.

I did, however, run into two separate errors.

https://gist.github.com/HugsLibRecordKeeper/9d4252b2b1e5d427c903915b5901c965

The first one is a known problem that I have been tracking for a while now.
https://gist.github.com/Eldulac/effccd476da09cdf4da93f5489f1ec84

It has been consistently happening on every RT game I have played recently, and it now seems that it is a problem with vanilla RT, and not related to other mods.

The second error is a new one to me, and happened twice during my test:
https://gist.github.com/Eldulac/e62386a8bc36025ace5038253518a5ad
It seems easily reproducible. Just load the save and speed up the game. It should happen eventually.

**Conclusion**
It seems that whatever caused this error in the past, is no longer reproducible, and has likely been fixed since then.
