### ISSUE TITLE
Sarai threw exception in WorkGiver BuildRoofs: System.NullReferenceException:

### ISSUE THREAD

**Issue by UndeadKitten** [cseelhoff/RimThreaded#402]
**Describe the bug**
Another red error that caused the log to popup, no noticeable issues. I was about 20 minutes into a new game (same save as my last 2 posts), with a freshly installed Rimworld and config folder. I only have Harmony and RimThreaded installed, and I don't have Royalty DLC. I've reduced the total worker threads to 4 to see if it will reduce the number of errors I get, but it seemed to have no effect. Also I'll mention that I've restarted my game after each new unique error to submit a report.
EDIT: Version was RT 1.2.3

**Error Log**
https://gist.github.com/UndeadKitten/75a2e4612ec584011f756d39d3bbc0cd

**Specs**
Operating System: Windows 10 Home 64-bit
Processor: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 CPUs), ~3.5GHz
Memory: 16384MB RAM
Card name: NVIDIA GeForce GTX 970

**Comment by Eldulac** [comment]
**[Tested on RT 1.3.2]**
I tested the save UndeadKitten had posted to another report here, which is about 5 minutes further into the game than the issue reported here.
[Esora (Permadeath).zip](https://github.com/cseelhoff/RimThreaded/files/6137437/Esora.Permadeath.zip)

I ran the game for about a week in-game, but was unable to replicate this problem, despite building roofs several times during the test.

I did, however, run into two separate errors.

https://gist.github.com/HugsLibRecordKeeper/9d4252b2b1e5d427c903915b5901c965

The first one is a known problem that I have been tracking for a while now.
https://gist.github.com/Eldulac/effccd476da09cdf4da93f5489f1ec84

It has been consistently happening on every RT game I have played recently, and it now seems that it is a problem with vanilla RT, and not related to other mods.

The second error is a new one to me, and happened twice during my test:
https://gist.github.com/Eldulac/e62386a8bc36025ace5038253518a5ad
It seems easily reproducible. Just load the save and speed up the game. It should happen eventually.

**Conclusion**
It seems that whatever caused this error in the past, is no longer reproducible, and has likely been fixed since then.
