### ISSUE TITLE
Exception in Verse.AI.ThinkNode_PrioritySorter TryIssueJobPackage: System.IndexOutOfRangeException:

### ISSUE THREAD

**Issue by UndeadKitten** [cseelhoff/RimThreaded#403]
**Describe the bug**
Another red error that caused the log to popup, no noticeable issues. I was about 25 minutes into a new game (same save as my last 3 posts), with a freshly installed Rimworld and config folder. I only have Harmony and RimThreaded installed, and I don't have Royalty DLC. The total worker threads is set to 4. Also I'll mention that I've restarted my game after each new unique error to submit a report. I will also include the save file in this post but I wouldn't think there's issues with the save file.
EDIT: Version was RT 1.2.3

**Error Log**
https://gist.github.com/UndeadKitten/72cc23c528355253ebff1cfad39a6c9c

**Specs**
Operating System: Windows 10 Home 64-bit
Processor: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 CPUs), ~3.5GHz
Memory: 16384MB RAM
Card name: NVIDIA GeForce GTX 970

**Save File**
https://drive.google.com/file/d/1xb5qEiFybpFa4Nt-YHJBjbazlfJI82MS/view?usp=sharing

**Comment by Eldulac** [comment]
**[Tested on RT 1.3.2]**
I tested the save in this report, and ran the game for about a week in-game, but was unable to replicate this problem. 

I did, however, run into two separate errors.

https://gist.github.com/HugsLibRecordKeeper/9d4252b2b1e5d427c903915b5901c965

The first one is a known problem that I have been tracking for a while now.
https://gist.github.com/Eldulac/effccd476da09cdf4da93f5489f1ec84

It has been consistently happening on every RT game I have played recently, and it now seems that it is a problem with vanilla RT, and not related to other mods.

The second error is a new one to me, and happened twice during my test:
https://gist.github.com/Eldulac/e62386a8bc36025ace5038253518a5ad
It seems easily reproducible. Just load the save and speed up the game. It should happen eventually.

**Conclusion**
It seems that whatever caused this error in the past, is no longer reproducible, and has likely been fixed since then.
