### ISSUE TITLE
Could not give thoughts: System.NullReferenceException:

### ISSUE THREAD

**Issue by UndeadKitten** [cseelhoff/RimThreaded#404]
**Describe the bug**
Another red error that caused the log to popup, no noticeable issues in-game. I was about 30 minutes into the same game as my last 4 posts, with a freshly installed Rimworld and config folder. I only have Harmony and RimThreaded installed, and I don't have Royalty DLC. The total worker threads is set to 4. I'll mention that I restart my game after each new unique error to submit a report. I will include an updated version of the save file once more.

EDIT: Upon loading the save back up, the raid event message is still there but the raider is gone (it was just one pawn I believe). There was also a caravan but they are also gone (I think I saw them leave), I'm guessing the caravan ran into the raider as they left the map. 
EDIT 2: I just found his corpse at the edge of the map, so yeah I do think the caravan killed him as they left, but for some reason there's 2 exact duplicates of his corpse.
EDIT 3: Version was RT 1.2.3

**To Reproduce**
1. A raid party just arrived during a heat wave, they will prepare for a while then attack
2. See error

**Error Log**
https://gist.github.com/UndeadKitten/5ac4db450d4e746c2ceaa444a82857f8

**Specs**
Operating System: Windows 10 Home 64-bit
Processor: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 CPUs), ~3.5GHz
Memory: 16384MB RAM
Card name: NVIDIA GeForce GTX 970

**Save File**
https://drive.google.com/file/d/1h1RA6THun_l_PDvjqU5oOdfkEQrNJjBo/view?usp=sharing

**Comment by Eldulac** [comment]
**[Tested on RT 1.3.2]**
I tested the save in this report, and ran the game for about a week in-game, but was unable to replicate this problem, despite triggering raids of varying sizes and types. The duplicate bodies were on the edge of the map as described, but nothing out of the ordinary happened regarding them.

I did, however, run into two separate kinds of errors.

https://gist.github.com/HugsLibRecordKeeper/9bf2134d6c07a1071df1ba04aa61132f

The first one is a known problem that I have been tracking for a while now.
https://gist.github.com/Eldulac/7749e835a68ed0156db29a78a3306162

It has been consistently happening on every RT game I have played recently, and it now seems that it is a problem with vanilla RT, and not related to other mods. It happens on various animal jobs, such as hunting, wandering, ingesting and hauling.

The second error is a new one to me, and happened once during my test:
https://gist.github.com/Eldulac/e62386a8bc36025ace5038253518a5ad
It seems easily reproducible. Just load the save and speed up the game. It should happen eventually.

**Conclusion**
It seems that whatever caused this error in the past, is no longer reproducible, and has likely been fixed since then.
