### ISSUE TITLE
 "More Faction Interaction (Continued)" No AI function

### ISSUE THREAD

**Issue by sophiachan213** [cseelhoff/RimThreaded#466]
**Describe the bug**
IMPORTANT: Please first search existing bugs to ensure you are not creating a duplicate bug report.  

* bug description here !!!
Upon creating new game pods won't land and there seems to be no functioning AI in animals (no movement).
If pawns are set to spawn standing they will not be able to move or accept forced work.

**To Reproduce (VERY IMPORTANT)**
1. Install "More Factions Interaction (Continued)"
2. Start new game
3. Watch as nothing happens

**Error Log**
There were no error logs about this.

**Mod List**
Harmony,
Core, Royalty,
HugsLib, More Faction Interaction (Continued),
RimThreaded

**Screenshots**
NA

**Comment by bababooeyy** [comment]
This happens due to a recent update to More Faction Interaction that broke some stuff. Gonna have to revert to an older version for the moment. GitHub version here
https://github.com/emipa606/MoreFactionInteraction/releases/tag/1.0.5

**Comment by bababooeyy** [comment]
I cannot reproduce this, can you provide a save maybe?

**Comment by Eldulac** [comment]
**[Tested on RT 1.3.2]**

I tested this issue on several fresh games, on different biomes and world map sizes (30 -100%). Both tribal and crashlanded starts were used.
I was not able to reproduce the described problem, despite several attempts. As far as starting the game on various settings goes, everything seems to work correctly. 

I used the most up-to-date version of "More Faction Interaction (Continued)"

**Conclusion**
Generating a new game with RT and "More faction Interaction (Continued)" seems to work fine. It is likely that the mod has been updated since this issue was encountered, which may have fixed the problem.
