### ISSUE TITLE
"Labels on Floor" game crash after loading up save and letting it run for a short while

### ISSUE THREAD

**Issue by madmax3004** [cseelhoff/RimThreaded#474]
**Describe the bug**
Game crashes within ~10 - 20 seconds after loading a specific save.

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Load up the save
2. Unpause
3. Wait for it to crash

**Error Log**
Player.log: https://pastebin.com/LN8gM8gT
Error.log: https://pastebin.com/bWT5qVN1

**Save file**

[Ravens#§#Ravens.zip](https://github.com/cseelhoff/RimThreaded/files/6052135/Ravens.Ravens.zip)

**Mod list (Preferably a RimPy compatible list.)**

[list.zip](https://github.com/cseelhoff/RimThreaded/files/6052148/list.zip)

NOTE:

This was tested with and without RuntimeGC to rule out that as a problem.

**Comment by Eldulac** [comment]
**[Tested on RT 1.3.2]**

I tested this issue on a fresh game, with only RT and "Labels on Floor" loaded. I was unable to reproduce the error described in this issue, despite numerous attempts at replicating the events of the issue. Changing labels of a test room, or deconstructing beds to force the label change, did not have any negative effect. This issue is therefore most likely related to other mods on the list, incompatibility problems, or a faulty load order.

PacMan and cat were consulted for advice on this test.

**Conclusion**
There is no indication of a problem between "Labels on Floor" and RT. Without further evidence of this error, we may consider this issue closed.
