### ISSUE TITLE
"Graphics Settings+" WorldPawnGC error

### ISSUE THREAD

**Issue by Eldulac** [cseelhoff/RimThreaded#489]
**Describe the bug**
While testing another issue regarding "Graphics Settings+" and "Camera+", I ran into this error after spawning around 50 pawns. Despite several attempts to reproduce this, I was unable to. I am not sure if this is related to the aforementioned mods, or an issue with RT itself, as I failed to reproduce the issue. There was no apparent effect from the error either.

**Steps to reproduce the behavior**
1. Start a new game
2. Spawn 50+ pawns through "StrangerInBlack"- events
3. Wait a while
4. If you are lucky, you might trigger this error

**Error Log**
https://gist.github.com/Eldulac/d57ef3d1576c0011e348a2b8770397ee
https://gist.github.com/HugsLibRecordKeeper/66be5290095c84bfc694473493518041

**Save file**
[WorldPawnGC issue.zip](https://github.com/cseelhoff/RimThreaded/files/6150593/WorldPawnGC.issue.zip)

**Mod list**
* Harmony
* Core
* Royalty (optional)
* HugsLib
* Mod Manager
* Camera+
* Graphics Settings+
* RimThreaded

**Comment by bababooeyy** [comment]
While testing the mass TraderCaravan Arrival error on 2.0.5 preview, I came across a similar error that seems to have the same root cause, however the error itself is not the same. I am copypasting the error individually as the Hugs log is flooded with BreadthTraverse errors

ModList:
Harmony
Core
Royalty
HugsLib
RimThreaded[2.0.5 Preview]

Error in WorldPawnGCTick(): System.NullReferenceException: Object reference not set to an instance of an object
  at Verse.PlayLog.AnyEntryConcerns (Verse.Pawn p) [0x00010] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.Planet.WorldPawnGC.GetCriticalPawnReason (Verse.Pawn pawn) [0x000cc] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.Planet.WorldPawnGC+<AccumulatePawnGCData>d__9.MoveNext () [0x00066] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.Planet.WorldPawnGC+<PawnGCPass>d__12.MoveNext () [0x0008a] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.Planet.WorldPawnGC.WorldPawnGCTick () [0x0006a] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimThreaded.WorldPawns_Patch.WorldPawnsTick (RimWorld.Planet.WorldPawns __instance) [0x0012e] in <0159967a552640fa8217f400cfa096c6>:0 
Verse.Log:Error(String, Boolean)
RimThreaded.WorldPawns_Patch:WorldPawnsTick(WorldPawns)
RimWorld.Planet.WorldPawns:RimWorld.Planet.WorldPawns.WorldPawnsTick_Patch1(WorldPawns)
RimThreaded.RimThreaded:PrepareWorkLists()
RimThreaded.RimThreaded:ProcessTicks(ThreadInfo)
RimThreaded.RimThreaded:InitializeThread(ThreadInfo)
RimThreaded.<>c__DisplayClass80_0:<CreateWorkerThread>b__0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Comment by pastorismylord** [comment]
unable to reproduce with the latest 2.x steam release.
