### ISSUE TITLE
"Rimefeller" Compatibility Issues

### ISSUE THREAD

**Issue by Alchemik123444** [cseelhoff/RimThreaded#503]
**Describe the bug**
Rimefeller - Do Until X orders on refiners dont stop on X and produce lots of errors in the debug log
UPDATE: The error only seems to occur when the bill is set to look everywhere instead of in a specific stockpile zone

**Steps to reproduce the behavior (VERY IMPORTANT)**
1. Get Rimefeller and Rimthreaded
2. Build any refiner, connect it with pipes to a full chemfuel tank, build a resource console, set a do until X bill and connect all to power
4. get a colonist to man the resource console so the refiners turn on
5. check debug log

**Error Log**
[Player.log](https://github.com/cseelhoff/RimThreaded/files/6392049/Player.log)

**Save file**

https://drive.google.com/file/d/1qdCu8yVhs0pKJFgu_O6iR-nJKU8dt0NA/view?usp=sharing

**Screenshots**
![image](https://user-images.githubusercontent.com/83351847/116411295-de39e000-a835-11eb-8cf4-fc6e52663a28.png)

**Mod list (Preferably a RimPy compatible list.)**
* Harmony
* Core
* Royalty (optional)
* Mod Manager (By Fluffy)
* Rimefeller
* RimThreaded

**Comment by bababooeyy** [comment]
Tested using provided test save.

Issue occurs as stated on 1.3.2, but seems to be fixed in the 2.0.7 preview. However, when I try to manually make another pawn prioritize work on the console, the pawn already there does not leave, instead both just stay there and use the console, with both pawns displaying the "using the resource console" action message. This does not produce an error, and does not happen without Rinthreaded. Without RT, the original pawn stops using the console. It even happens with many pawns. I did not notice any effect on gameplay, the extraction speeds seemed the same. However, I have never used Rimefeller before so I don't really know what is supposed to happen. I would appreciate it if someone who has experience with the mod can verify my findings. 
![Screenshot (279)](https://user-images.githubusercontent.com/77920755/116527155-f6306300-a90c-11eb-91d5-b47caebd9834.png)
![Screenshot (280)](https://user-images.githubusercontent.com/77920755/116527159-f892bd00-a90c-11eb-9eda-d15ff9564416.png)
![Screenshot (281)](https://user-images.githubusercontent.com/77920755/116527168-faf51700-a90c-11eb-8748-50564a883d1e.png)

**Comment by Alchemik123444** [comment]
> Tested using provided test save.
> 
> Issue occurs as stated on 1.3.2, but seems to be fixed in the 2.0.7 preview. There are no error spam when loading the test save with 2.0.7.
> 
> However, when I try to manually make another pawn prioritize work on the console, the pawn already there does not leave, instead both just stay there and use the console, with both pawns displaying the "using the resource console" action message. This does not produce an error, and does not happen without Rinthreaded. Without RT, the original pawn stops using the console. It even happens with many pawns. I did not notice any effect on gameplay, the extraction speeds seemed the same. However, I have never used Rimefeller before so I don't really know what is supposed to happen. I would appreciate it if someone who has experience with the mod can verify my findings.
> ![Screenshot (279)](https://user-images.githubusercontent.com/77920755/116527155-f6306300-a90c-11eb-91d5-b47caebd9834.png)
> ![Screenshot (280)](https://user-images.githubusercontent.com/77920755/116527159-f892bd00-a90c-11eb-9eda-d15ff9564416.png)
> ![Screenshot (281)](https://user-images.githubusercontent.com/77920755/116527168-faf51700-a90c-11eb-8748-50564a883d1e.png)

The pawns should not stack up at the resource console, only one is required to have the refineries work
