### ISSUE TITLE
LVM deep storage mod is not compatible with RimThreaded; items scatter out of containers

### ISSUE THREAD

**Issue by cseelhoff** [cseelhoff/RimThreaded#51]
Seems to be a problem in GenSpawn.Spawn. Probably needs to be transpiled, rather than prefix'd. Only 2 lines are added, both are simple null checks.

https://github.com/cseelhoff/RimThreaded/blob/master/Source/GenSpawn.cs#L63-L67

            //added null check
            if (null != newThing)
            {
                //added null check
                if (null != newThing.def)

**Comment by Ataman** [comment]
After checking the Deep Storage mod I found a Transpiler for the GenSpawn.Spawn method. Your prefix returns false, thus preventing the original method (which was transpiled) from being run.

Since this is just a null check, I suggest changing the prefix to just contain the check and prevent further execution only in case newThing is null.

It's probably also sensible to figure out what's calling GenSpawn.Spawn with newThing set to null.
