### ISSUE TITLE
No hauling between storage areas with different priority levels

### ISSUE THREAD

**Issue by TheVillageGuy** [cseelhoff/RimThreaded#666]
No hauling between storage areas with different priority levels, even though there are idle colonists.

Example: two raw food storage areas, one preferred, one critical. There is raw food in the preferred, none in critical. The food will not be hauled, until the settings of the area are changed.

### **Steps to reproduce the behavior
1. Make several areas with the same settings, but different priority levels
2. If they're not hauling from a lower to a higher priority level, change the level of the relevant area and they'll start hauling

I am not sure if having the exact same settings in step 1 is a requirement, just the priorities may be enough.

**Comment by sealvessel** [comment]
I agree. I had a freezer next to my stove with a higher priority and it just gave me an error when trying to haul.

**Comment by Avalre** [comment]
Same issue. In my case, changing the priority level does not work. Sometimes, I am able to fix the issue by completely deleting and remaking the zone, however, this does not always work (no clue why). For me, this issue occurred on my ~85 mods game, however, this issue being reproducible on vanilla+RT by OP suggests that the issue is with RT and not with any mods. 

![InkedRimWorldWin64_4XHRzdmwCZ_LI](https://user-images.githubusercontent.com/90802878/133675933-23b99e7e-11f6-4b7b-83c6-4778a03fce35.jpg)

In the above image, there is a clear path to the fridge I want the bodies to be hauled to, however, the option to prioritize hauling is unavailable. I have triple-checked the settings on the fridge stockpile zone (issue persists even with allow all and critical priority), the path to the fridge from the body, and my colonist's allowed zones (unrestricted). 

Hugslib Log:
[https://gist.github.com/1fe51f631b6cd353451a337543b282af](url)

Error Log: 
None found in the directory designated

Player Log: 
[Player.log](https://github.com/cseelhoff/RimThreaded/files/7180604/Player.log)

Save File (bug is fixable by deleting and remaking zones at least by my testing):
[Coalition of Pepega - Bugged Out.zip](https://github.com/cseelhoff/RimThreaded/files/7180614/Coalition.of.Pepega.-.Bugged.Out.zip)

Save File (bug is not fixable by deleting and remaking zones by my testing):
[Coalition of Pepega - Bugged Out 2.zip](https://github.com/cseelhoff/RimThreaded/files/7180643/Coalition.of.Pepega.-.Bugged.Out.2.zip)

Please let me know if you need any other information! I will try to check here daily, but I am also reachable through the RT discord: Avalre#2969

**Comment by TheVillageGuy** [comment]
> Same issue. In my case, changing the priority level does not work. 
Not exactly as from your image it seems that your can't give the hauling instruction manually, which I can. If you can't do it manually, it's not going to happen automatically.

I would recommend also posting a picture with all the settings from the destination area, as, under normal circumstances, this would be caused by a configuration error. Therefore it is of added value to the author to see under which circumstances it is failing for you.

**Comment by TheVillageGuy** [comment]
The bug no longer occurs with the latest beta.
