### ISSUE TITLE
[Smart Speed] Speed 4 button doesn't appear, but works as intended

### ISSUE THREAD

**Issue by Superfly-Johnson** [cseelhoff/RimThreaded#740]
# **Non-Vanilla Bug Report**
Smart speed's speed 4 button doesn't show up with rimthreaded installed.
### **Describe the bug**
Smart Speed's speed 4 button doesn't show up, but works as intended.

### **Steps to reproduce the behavior (VERY IMPORTANT)**
1. Use the [modlist](https://gist.githubusercontent.com/Superfly-Johnson/79f8ccee98916d7177922fa458ddf5a0/raw/113f98658c17552c580050a6a09387fc39694cc2/rtbugreport.xml)
2. Start a new game
3. Notice the lack of a speed 4 button
4. Press the speed 4 button to notice it's working.
#### **Player.log (Optional)**
[PlayerLog](https://gist.github.com/Superfly-Johnson/79f8ccee98916d7177922fa458ddf5a0)

### **Mod list (Preferably a RimPy compatible list.)** [?](https://github.com/cseelhoff/RimThreaded/wiki/Q%26A#what-mod-organizer-should-i-use)
```
<?xml version="1.0" encoding="utf-8"?>
<ModsConfigData>
    <version>1.3.3200 rev726</version>
    <activeMods>
        <li>brrainz.harmony</li>
        <li>ludeon.rimworld</li>
        <li>ludeon.rimworld.royalty</li>
        <li>ludeon.rimworld.ideology</li>
        <li>sarg.smartspeed</li>
        <li>majorhoff.rimthreaded</li>
    </activeMods>
    <knownExpansions>
        <li>ludeon.rimworld</li>
        <li>ludeon.rimworld.royalty</li>
        <li>ludeon.rimworld.ideology</li>
    </knownExpansions>
</ModsConfigData>
```
* Harmony
* Core
* Royalty
* Ideology
* Smart Speed
* RimThreaded

**Comment by Niilo007** [comment]
Smart speed is not needed, and not recommended to be used with RimThreaded, please read the wiki for more info!
Im closing this issue, as its not consider one.

---

**Please see:**

* [Q&A](https://github.com/cseelhoff/RimThreaded/wiki/Q&A)

* [Mod Compatibility](https://github.com/cseelhoff/RimThreaded/wiki/Mod-Compatibility)

* [Known Issues](https://github.com/cseelhoff/RimThreaded/projects/1?fullscreen=true)

* The [Community Modpack](https://github.com/pastorismylord/Community-Modpack)

* This [Mod Order Guide](https://rwom.fandom.com/wiki/Mod_Order_Guide)

**Address the problems in your mod list before asking for help or submitting errors & bug reports!**

* You can submit a bug report [here](https://github.com/cseelhoff/RimThreaded/issues/new/choose)

* If your submitted issue gets closed and the bug is still happening you can re open the issue.

---
